### PR TITLE
add request headers

### PR DESCRIPTION
**Pull request by JamesKyburz**

### CODE REVIEW

**Comment by JamesKyburz** [comment]
Could this please be merged?

**Comment by mikeal** [comment]
Merged and added you as a committer :)

**Comment by JamesKyburz** [comment]
Great, thanks!

Any chance you could add me to npm too?

**Comment by JamesKyburz** [comment]
@mikeal Could we please publish to npm?

**Comment by mikeal** [comment]
v0.6.0

**Comment by JamesKyburz** [comment]
Nice 🎉

**Pull request merged**
